# Generated by Django 4.2.2 on 2023-06-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountriesMarketRiskPremium',
            fields=[
                ('country', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('continent', models.CharField(max_length=255)),
                ('total_equity_risk_premium', models.FloatField()),
                ('country_risk_premium', models.FloatField()),
                ('datestamp', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dim_countries_market_risk_premium',
                'managed': False,
            },
        ),
    ]
