# Generated by Django 4.2.2 on 2023-06-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StocksUpgradedowngrade',
            fields=[
                ('published_date', models.CharField(max_length=255)),
                ('news_url', models.CharField(max_length=255)),
                ('news_title', models.CharField(max_length=255)),
                ('news_base_url', models.CharField(max_length=255)),
                ('news_publisher', models.CharField(max_length=255)),
                ('new_grade', models.CharField(max_length=255)),
                ('previous_grade', models.CharField(max_length=255)),
                ('grading_company', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('price_when_posted', models.FloatField()),
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dim_tickers_stocks_upgradedowngrade',
                'managed': False,
            },
        ),
    ]
