# Generated by Django 4.2.2 on 2023-06-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stockshstemployees',
            fields=[
                ('cik', models.CharField(max_length=255)),
                ('acceptanceTime', models.CharField(max_length=255)),
                ('periodOfReport', models.CharField(max_length=255)),
                ('companyName', models.CharField(max_length=255)),
                ('formType', models.CharField(max_length=255)),
                ('filingDate', models.CharField(max_length=255)),
                ('employeeCount', models.IntegerField()),
                ('source', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dim_ticker_stocks_hst_employees_fmp',
                'managed': False,
            },
        ),
    ]
