# Generated by Django 4.2.2 on 2023-06-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StocksPress',
            fields=[
                ('date', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dim_tickers_stocks_press',
                'managed': False,
            },
        ),
    ]
