# Generated by Django 4.2.2 on 2023-06-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StocksRatings',
            fields=[
                ('date', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=255)),
                ('rating_score', models.IntegerField()),
                ('rating_recommendation', models.CharField(max_length=255)),
                ('rating_details_dcf_score', models.IntegerField()),
                ('rating_details_dcf_recommendation', models.CharField(max_length=255)),
                ('rating_details_roe_score', models.IntegerField()),
                ('rating_details_roe_recommendation', models.CharField(max_length=255)),
                ('rating_details_roa_score', models.IntegerField()),
                ('rating_details_roa_recommendation', models.CharField(max_length=255)),
                ('rating_details_de_score', models.IntegerField()),
                ('rating_details_de_recommendation', models.CharField(max_length=255)),
                ('rating_details_pe_score', models.IntegerField()),
                ('rating_details_pe_recommendation', models.CharField(max_length=255)),
                ('rating_details_pb_score', models.IntegerField()),
                ('rating_details_pb_recommendation', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dim_tickers_stocks_ratings',
                'managed': False,
            },
        ),
    ]
