# Generated by Django 4.2.2 on 2023-06-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StocksHstEmployees',
            fields=[
                ('cik', models.CharField(max_length=255)),
                ('acceptance_time', models.CharField(max_length=255)),
                ('period_of_report', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('form_type', models.CharField(max_length=255)),
                ('filing_date', models.CharField(max_length=255)),
                ('employee_count', models.IntegerField()),
                ('source', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dim_ticker_stocks_hst_employees_fmp',
                'managed': False,
            },
        ),
    ]
