# Generated by Django 4.2.2 on 2023-06-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StocksInsidertrades',
            fields=[
                ('filing_date', models.CharField(max_length=255)),
                ('transaction_date', models.CharField(max_length=255)),
                ('reporting_cik', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(max_length=255)),
                ('securities_owned', models.CharField(max_length=255)),
                ('company_cik', models.CharField(max_length=255)),
                ('reporting_name', models.CharField(max_length=255)),
                ('type_of_owner', models.CharField(max_length=255)),
                ('acquistion_or_disposition', models.CharField(max_length=255)),
                ('form_type', models.CharField(max_length=255)),
                ('securities_transacted', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('security_name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dim_tickers_stocks_insidertrades',
                'managed': False,
            },
        ),
    ]
