# Generated by Django 4.2.2 on 2023-06-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StocksOffExchange',
            fields=[
                ('date', models.CharField(max_length=255)),
                ('otc_short', models.IntegerField()),
                ('otc_total', models.IntegerField()),
                ('dpi', models.FloatField()),
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dim_tickers_stocks_off_exchange',
                'managed': False,
            },
        ),
    ]
