# Generated by Django 4.2.2 on 2023-06-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StocksEarningsSurprises',
            fields=[
                ('date', models.CharField(max_length=255)),
                ('actual_earning_result', models.FloatField()),
                ('estimated_earning', models.FloatField()),
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dim_tickers_stocks_earnings_surprises',
                'managed': False,
            },
        ),
    ]
