# Generated by Django 4.2.2 on 2023-06-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StocksEmployees',
            fields=[
                ('cik', models.CharField(max_length=255)),
                ('filing_date', models.CharField(max_length=255)),
                ('acceptance_time', models.CharField(max_length=255)),
                ('period_of_report', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('form_type', models.CharField(max_length=255)),
                ('employee_count', models.IntegerField()),
                ('source', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dim_tickers_stocks_employees',
                'managed': False,
            },
        ),
    ]
