# Generated by Django 4.2.2 on 2023-06-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StocksEarningsCalls',
            fields=[
                ('date', models.CharField(max_length=255)),
                ('quarter', models.IntegerField()),
                ('year', models.IntegerField()),
                ('content', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dim_tickers_stocks_earnings_calls',
                'managed': False,
            },
        ),
    ]
