# Generated by Django 4.2.2 on 2023-06-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StocksEsgrisk',
            fields=[
                ('date', models.CharField(max_length=255)),
                ('cik', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('form_type', models.CharField(max_length=255)),
                ('accepted_date', models.CharField(max_length=255)),
                ('environmental_score', models.FloatField()),
                ('social_score', models.FloatField()),
                ('governance_score', models.FloatField()),
                ('esg_score', models.FloatField()),
                ('url', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dim_tickers_stocks_esgrisk',
                'managed': False,
            },
        ),
    ]
