# Generated by Django 4.2.2 on 2023-06-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StocksKeyExecutives',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('pay', models.CharField(max_length=255)),
                ('currency_pay', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('year_born', models.CharField(max_length=255)),
                ('title_since', models.FloatField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dim_tickers_stocks_key_executives',
                'managed': False,
            },
        ),
    ]
